status-updates: Add summary of meeting on Friday, June 2, 2023
open-education-hub/meeting-notes pull request #6
Opened 2023-06-02 08:57 UTC by teodutu

2023-06-02 09:11 UTC, Sergiu121 requested changes
Needs some changes and context. Plus, there's some wrong information.

2023-06-02 09:11 UTC, sergiu121 commented on status-updates/2023/2023-06-02.md
> +* a third repo will only contain config files that specify which parts of the content are rendered and how.
This is wrong. The third repo will contain the local administrative content such as deadlines, links to class registers and others.

2023-06-02 09:11 UTC, sergiu121 commented on status-updates/2023/2023-06-02.md
> +
You missed something:

```suggestion
SW: We're just trying to find edge cases at this point.
```

2023-06-02 09:11 UTC, sergiu121 commented on status-updates/2023/2023-06-02.md
> +Why don't we store configs in the fork of the upstream repo?
The issue is not about the configs. The issue is about admin content.

2023-06-02 09:11 UTC, sergiu121 commented on status-updates/2023/2023-06-02.md
> +* a third repo will only contain config files that specify which parts of the content are rendered and how.
You missed the context here. We want the students to actually use the local organization's repository, not the OEH one. The OEH content is just a demo, a showcase. This should this be forked afterwards and changed.

2023-06-02 09:11 UTC, sergiu121 commented on status-updates/2023/2023-06-02.md
> +### Security Summer School
You missed here the discussion about how the builder should work. We talked about whether it would use submodules, a link, or another command in the GitHub Action. This is an open issue that we have to account for.

2023-06-02 09:16 UTC, VladNastase commented on status-updates/2023/2023-06-02.md
> +RăzvanD, Vlad, Teo, Alex, Gabi, Sergiu, Liza, Mihai
I was not able to participate in the meeting today

2023-06-12 08:55 UTC, gabrielmocanu approved these changes

2023-06-12 08:55 UTC, merged